spring:
  application:
    name: Api-Gateway
    
  cloud:
    gateway:
      routes:
      - id: product-service
        #uri: lb://PRODUCT-SERVICE
        uri: http://localhost:8082
        predicates:
         - Path=/products/**

server:
  port: 8087

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
      